name: commit message test
on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name : get pr body
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          PULL_NUM: ${{ github.event.number }}
        run: echo "$PR_BODY"
      - name : update pr
        run: $(curl --user "liampuk" --request PATCH --data '{"body":"update-body-test"}' https://api.github.com/repos/liampuk/actionsTest/pulls/$PULL_NUM)
