
name: Terraform Formatter

on:
  pull_request

jobs:
  format-pr:
    name: Format PR
    runs-on: ubuntu-latest
    outputs:
      formatted_pr: ${{ steps.format_pr.outputs.formatted_pr }}
    steps:
      - id: format_pr
        run: |
          declare formatted_pr=$(echo "${{ github.event.pull_request.body }}" | grep -E '(Terraform will perform|Plan: |\ *#).*')
          formatted_pr="${formatted_pr//'%'/'%25'}"
          formatted_pr="${formatted_pr//$'\n'/'%0A'}"
          formatted_pr="${formatted_pr//$'\r'/'%0D'}"
          echo ::set-output name=formatted_pr::$formatted_pr
          curl --user "liampuk" \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --request PATCH \
          --data '{"body": "${{ formatted_pr }}"}' \
          https://api.github.com/repos/liampuk/actionsTest/pulls/${{ github.event.number }} 
