name: commit message test
on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name : get pr body
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          PULL_NUM: ${{ github.event.number }}
        run: |
          curl --user "liampuk" \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --request PATCH \
          --data '{"body":"$PR_BODY updated"}' \
          https://api.github.com/repos/liampuk/actionsTest/pulls/${{ github.event.number }} 
