name: commit message test
on: pull_request

jobs:
  parse-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set var
        run: TEST = "test-var-1"
      - name : update pr
        run: |
          curl --user "liampuk" \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --request PATCH \
          --data '{"body": $TEST-Var}' \
          https://api.github.com/repos/liampuk/actionsTest/pulls/${{ github.event.number }} 
