
name: commit message test
on: pull_request

jobs:
  parse-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name : get pr body
        run : |
          echo "$({{ github.event.pull_request.body }} | grep -E '(Terraform will perform|Plan: |\ *#).*')" > original-pr-body
      - name : set var
        run: |
          echo ::set-env name=PR_BODY::$(cat original-pr-body)
      - name : update pr
        run : |
          curl --user "liampuk" \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --request PATCH \
          --data '{"body": "${{ env.PR_BODY }}"}' \
          https://api.github.com/repos/liampuk/actionsTest/pulls/${{ github.event.number }} 
