name: commit message test
on: pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name : GITHUB CONTEXT
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: echo "$PR_BODY"
