name: commit message test
on: pull_request

jobs:
  parse-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name : update pr
        env: 
          PR_BODY: test
        run: |
          curl --user "liampuk" \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --request PATCH \
          --data '{"body": ${{ env.PR_BODY }}}' \
          https://api.github.com/repos/liampuk/actionsTest/pulls/${{ github.event.number }} 
